---

- hosts: localhost

- hosts: "{{ cluster_name }}_node"

  become: true

  vars:

    kubeadm_packages:
      - docker.io
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  tasks:

    - name: Reset kubeadm
      command: /usr/bin/kubeadm reset
      async: 45
      poll: 0      
      ignore_errors: true

    - name: Remove packages
      apt:
        name: '{{ kubeadm_packages | list }}'
        state: absent
        update_cache: true
      ignore_errors: true

    - name: Remove immutable bit on /var/lib/kubelet
      command: chattr -Ri /var/lib/kubelet/
      ignore_errors: true

    - name: Remove kubernetes directorys
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /run/kubernetes
      ignore_errors: true

- hosts: "{{ cluster_name }}_master"

  become: true

  vars:

    kubeadm_packages:
      - docker.io
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni  

  tasks:

    - name: Reset kubeadm
      command: /usr/bin/kubeadm reset
      async: 45
      poll: 0
      ignore_errors: true
      
    - name: Remove packages
      apt:
        name: '{{ kubeadm_packages | list }}'
        state: absent
        update_cache: true
      ignore_errors: true

    - name: Remove kubernetes directorys
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /run/kubernetes
        - /var/lib/etcd
      ignore_errors: true        

        
        
