---

- hosts: localhost
  gather_facts: false

  roles:

    - role: admission_token
      tags:
        - token

  tasks:

    - debug:
        var: admission_token
      tags:
        - token


- hosts: "{{ cluster_name }}_master"

  user: ds

  become: true

  pre_tasks:

    - name: Read token from file
      include_vars: cfg/{{ cluster_name }}/token.yml

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes          

  tasks:

    # Implements Step 2 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Initialize master
      command: kubeadm init --token {{ admission_token }}
      args:
        creates: /etc/kubernetes/pki
      register: master_init
      ignore_errors: true
      tags:
        - master
        - init

      # Not 100% sure that the creates clause is correct

- hosts: localhost

  tasks:

    - set_fact:
        cluster_master: "{{ groups[ cluster_name + '_master' ][0] }}"

    - name: Save master_ip_address
      copy:
        dest: cfg/{{ cluster_name }}/master_ip_address.yml
        content: "master_ip_address: {{ hostvars[ cluster_master ]['ansible_default_ipv4']['address'] }}"

- hosts: "{{ cluster_name }}_node"

  user: ds

  become: true

  pre_tasks:

    - name: Read token from file
      include_vars: cfg/{{ cluster_name }}/token.yml
      
    - name: Read master_ip_address from file
      include_vars: cfg/{{ cluster_name }}/master_ip_address.yml

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes    

  tasks:

    # Implements Step 3 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - debug:
        var: admission_token
      run_once: true

    - debug:
        var: master_ip_address
      run_once: true

    - name: Join nodes to cluster
      command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: node_join
      ignore_errors: true
      tags:
        - nodes
        - join

    - debug:
        var: node_join.stdout_lines

      # Not 100% sure that the creates clause is correct

- hosts: "{{ cluster_name }}_master"

  user: ds

  become: true

  tasks:

    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Install pod network
      command: /usr/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://git.io/weave-kube-1.6
      register: pod_network
      tags:
        - master
        - network
      ignore_errors: true

    - debug:
        var: pod_network.stdout_lines        

    - name: Copy
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: cfg/{{ cluster_name }}/admin.conf
        flat: true
      tags:
        - master
        - remote
