# Pass in cluster_name
# WARNINGL This is untested in its current form.  The specific commands are tested/work, but the parsing and display of results is untested...
# Todo: Add support for Heapster
---

- hosts: localhost

  gather_facts: false

  tasks:

    - name: Install Dashboard
      command: kubectl -o json --kubeconfig cfg/{{ cluster_name }}/admin.conf create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
      register: dashboard_raw

    - set_fact:
        dashboard_output: "{{ dashboard_raw.stdout|from_json }}"

    - name: Install WeaveScope
      command: kubectl -o json --kubeconfig cfg/{{ cluster_name }}/admin.conf apply -f https://cloud.weave.works/launch/k8s/weavescope.yaml
      register: weavescope_raw

    - set_fact:
        weavescope_output: "{{ weavescope_raw.stdout|from_json }}"

    - debug:
        var: dashboard_output

    - debug:
        var: weavescope_output




     
