---

- name: stat tokens/cluster_name.yml
  stat:
    path:  cfg/{{ cluster_name }}/token.yml
  register: token_file

- include: retrieve.yml
  when: token_file.stat.exists

- include: generate.yml
  when: not token_file.stat.exists


